on:
  push:
    branches:
      - master
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PW: ${{ secrets.DOCKER_PW }}

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

      # In an ideal world, skaffold and kustomize would be in a github action (and we'd pin these binary versions)
    - name: Install skaffold
      run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/

    - name: Cache skaffold image builds & config
      uses: actions/cache@v2
      with:
        path: ~/.skaffold/
        key: fixed-${{ github.sha }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Install kustomize
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && sudo mv kustomize /usr/local/bin

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    # - name: Log in to DigitalOcean Container Registry with short-lived credentials
    #   run: doctl registry login --expiry-seconds 600

    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save nodeapp

    - name: Deploy to cluster with Skaffold
      run: skaffold run 
